license="${mod_license}"

issueTrackerURL="https://github.com/Sinytra/Launchpad/issues"

[[mods]]

modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

displayURL="https://github.com/Sinytra/Launchpad"

logoFile="logo.png"

authors="Su5eD"

description='''
Develop for NeoForge in the Fabric way. Bring your mod metadata, entrypoints and classtweakers over.
'''
